# ===============================================
# Agroforestry Platform - Data Ingestion Config
# ===============================================
#
# Define all state-specific data sources here.
# The importer script will automatically process any file listed.
#
# - state_code: Two-letter state abbreviation (e.g., "NY").
# - file_path:  Path to the data file within the 'data/' directory.
# - layer_name: The specific layer to read from the file.
# - table_name: The final table name in the database.
# - is_spatial: 'true' for map data, 'false' for plain tables.
#

---
- state_code: "NY"
  file_path: "NYS_2024_Tax_Parcels_Public_2504.gdb"
  layer_name: "NYS_Tax_Parcels_Public"
  table_name: "nys_parcels"
  is_spatial: true

- state_code: "NY"
  file_path: "NYS_2024_Tax_Parcels_Public_2504.gdb"
  layer_name: "NYS_Property_Class_Codes"
  table_name: "nys_property_class_codes"
  is_spatial: false

# --- Add Data for a New State Here ---
# Example for Pennsylvania (once you have the data)
#
# - state_code: "PA"
#   file_path: "Pennsylvania/Parcels_2024.gpkg"
#   layer_name: "pasda_parcels"
#   table_name: "pa_parcels"
#   is_spatial: true