# ===============================================
# Agroforestry Platform - Data Ingestion Config
# ===============================================
#
# NEW:
# - source_type: 'file' for local files, 'arcgis_rest' for web services.
# - url: The base URL of the ArcGIS REST Service.
# - file_path: Path for local files within the 'data/' directory.
#

---
# --- Local File Sources ---
- state_code: "NY"
  source_type: "file"
  file_path: "NYS_2024_Tax_Parcels_Public_2504.gdb"
  layer_name: "NYS_Tax_Parcels_Public"
  table_name: "nys_parcels"
  is_spatial: true

- state_code: "NY"
  source_type: "file"
  file_path: "NYS_Dams.gpkg"
  layer_name: null
  table_name: "nys_dams"
  is_spatial: true

# --- ArcGIS REST Service Sources ---
- state_code: "NY"
  source_type: "arcgis_rest"
  url: "https://gisservices.dec.ny.gov/arcgis/rest/services/GW/Unconsolidated_Aquifers_250K_Upstate_NY/MapServer"
  layer_name: "1" # Layer ID for 'Confined Unconsolidated Aquifers 250K'
  table_name: "nys_aquifers_confined"
  is_spatial: true

- state_code: "NY"
  source_type: "arcgis_rest"
  url: "https://gisservices.dec.ny.gov/arcgis/rest/services/GW/Unconsolidated_Aquifers_250K_Upstate_NY/MapServer"
  layer_name: "2" # Layer ID for 'Main Unconsolidated Aquifers 250K'
  table_name: "nys_aquifers_main"
  is_spatial: true

